/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.9.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 6/26/2020
 ***********************************************************************************************/

#ifndef REBUTTON_IMPL
#define REBUTTON_IMPL

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"
#include "parson.h"

/**
* Type definition
*/

/**
* Device telemetries related methods.
*/

double Battery_Telemetry_ReadBatteryVoltage();

char* PushButton_Telemetry_ReadSingleClick();

char* PushButton_Telemetry_ReadDoubleClick();

char* PushButton_Telemetry_ReadTripleClick();

char* PushButton_Telemetry_ReadLongPress();

char* PushButton_Telemetry_ReadSuperLongPress();

/**
* Device properties related methods.
*/

char* DeviceInfo_Property_GetManufacturer();

char* DeviceInfo_Property_GetModel();

char* DeviceInfo_Property_GetSwVersion();

char* DeviceInfo_Property_GetOsName();

char* DeviceInfo_Property_GetProcessorArchitecture();

char* DeviceInfo_Property_GetProcessorManufacturer();

long DeviceInfo_Property_GetTotalStorage();

long DeviceInfo_Property_GetTotalMemory();

bool PushButton_Property_ActionCountCallback(int actionCount);

/**
* Device commands related methods.
*/

// Callbacks to handle the confirmation result of sending telemetry
void SendTelemetry_Succeeded_Callback(const char* interfaceName);
void SendTelemetry_Error_Callback(const char* interfaceName);

// Callbacks to handle the confirmation result of reporting property
void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName);
void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName);

#ifdef __cplusplus
}
#endif

#endif // REBUTTON_IMPL
